version: 2
jobs:
  unit-tests:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - run:
          name: setup
          command: |
            make develop
      - run:
          name: lint
          command: |
            make lint
      - run:
          name: run tests
          command: |
            make test
  large-tests:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - run:
          name: run large tests
          command: |
            make large-test

workflows:
  version: 2
  workflow:
    jobs:
    - unit-tests
    - large-tests

